spring:
  application:
    name: BookManager
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081