spring:
  application:
    name: BookManager
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    username: user
    password: password
    port: 5672
    host: localhost

server:
  port: 8081

rabbit:
  queue:
    name: book_queue